### ISSUE TITLE
possible bug with rooms.get

### ISSUE THREAD

**Issue by bradh11** [CiscoDevNet/webexteamssdk#114] opened 2020-06-01 00:32 UTC
when running `api.rooms.get(roomId='myroomid')` i am seeing that the class object gets all attributes from _json_data except `ownerId`.  I am trying to leverage the SDK to check for rooms within an organization and think it would be easier if i didnt have to fetch the ownerId from inside the _json_data dictionary within the class object for the returned room.

Screenshot below shows the attribute in the dict but not in the root object.
![image](https://user-images.githubusercontent.com/18483910/83366544-c932a380-a37d-11ea-8f8c-86f273b56127.png)

is this a bug, or by design?

**Comment by sQu4rks** [comment] 2020-06-17 19:46
Not by design @bradh11. Thanks for raising this. I'll be adding it to the property list and create a PR so that it is included in the next release. In the meantime you can just access the property over the dict itself.

**Comment by sQu4rks** [comment] 2020-06-18 17:56
Hi @bradh11 

I have added the ownerId to the property list of the room object. You can try the code by installing  my development branch (`pip3 install git+https://github.com/sQu4rks/webexteamssdk@issue-114`) or wait until the PR gets merged and a new release gets pushed. 

Let me know if this resolves your issue.

**Closed** 2020-06-19 16:17 UTC
Labels: bug
